<?php

namespace App\Providers;

use App\Models\Category;
use App\Models\CreditNote;
use App\Models\Customer;
use App\Models\CustomerCreditTransaction;
use App\Models\CustomerGroup;
use App\Models\GoodsReceipt;
use App\Models\Group;
use App\Models\Invoice;
use App\Models\JournalEntryLine;
use App\Models\Menu;
use App\Models\Payment;
use App\Models\PriceList;
use App\Models\PriceListItem;
use App\Models\Product;
use App\Models\PurchaseOrder;
use App\Models\PurchaseReturn;
use App\Models\SalesOrder;
use App\Models\SalesReturn;
use App\Models\Setting;
use App\Models\StockAdjustment;
use App\Models\Supplier;
use App\Models\Unit;
use App\Observers\AuditObserver;
use App\Observers\CreditNoteObserver;
use App\Observers\CustomerObserver;
use App\Observers\GoodsReceiptObserver;
use App\Observers\InvoiceObserver;
use App\Observers\JournalEntryLineObserver;
use App\Observers\PaymentObserver;
use App\Observers\PriceListItemObserver;
use App\Observers\PriceListObserver;
use App\Observers\ProductObserver;
use App\Observers\PurchaseOrderObserver;
use App\Observers\PurchaseReturnObserver;
use App\Observers\ReturnObserver;
use App\Observers\SalesOrderObserver;
use Illuminate\Support\Facades\Gate;
use App\Services\AuditService;
use App\Services\BatchService;
use App\Services\CategoryService;
use App\Services\CreditNoteService;
use App\Services\CreditService;
use App\Services\CustomerAnalyticsService;
use App\Services\CustomerGroupService;
use App\Services\CustomerService;
use App\Services\ExpiryMonitoringService;
use App\Services\FifoService;
use App\Services\FulfillmentService;
use App\Services\GoodsReceiptService;
use App\Services\InventoryAnalyticsService;
use App\Services\InventoryService;
use App\Services\InventoryValuationService;
use App\Services\InvoiceService;
use App\Services\PaymentService;
use App\Services\PermissionService;
use App\Services\PosService;
use App\Services\PriceListService;
use App\Services\PriceRuleService;
use App\Services\PricingService;
use App\Services\CentralApprovalService;
use App\Services\PrintDocumentService;
use App\Services\PurchaseOrderService;
use App\Services\PurchaseReturnService;
use App\Services\ReceiptService;
use App\Services\RefundService;
use App\Services\ReservationService;
use App\Services\SalesOrderService;
use App\Services\SalesReturnService;
use App\Services\SettingsService;
use App\Services\StatementService;
use App\Services\SupplierAnalyticsService;
use App\Services\SupplierService;
use App\Services\UnitService;
use App\Services\SalesReportService;
use App\Services\ProfitAnalysisService;
use App\Services\InventoryReportService;
use App\Services\CustomerReportService;
use App\Services\SupplierReportService;
use App\Services\ProcurementReportService;
use App\Services\TaxReportService;
use App\Services\PaymentReportService;
use App\Services\DashboardAnalyticsService;
use App\Services\KpiService;
use App\Services\ScheduledReportService;
use App\Services\AdvanceService;
use App\Services\BankingService;
use App\Services\ExportService;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton(PermissionService::class);
        $this->app->singleton(AuditService::class);
        $this->app->singleton(SettingsService::class);
        $this->app->singleton(CategoryService::class);
        $this->app->singleton(UnitService::class);
        $this->app->singleton(CustomerGroupService::class);
        $this->app->singleton(SupplierService::class);
        $this->app->singleton(PriceListService::class);
        $this->app->singleton(PriceRuleService::class);
        $this->app->singleton(PricingService::class);
        $this->app->singleton(CustomerService::class);
        $this->app->singleton(CreditService::class);
        $this->app->singleton(StatementService::class);
        $this->app->singleton(CustomerAnalyticsService::class);
        $this->app->singleton(PurchaseOrderService::class);
        $this->app->singleton(CentralApprovalService::class);
        $this->app->singleton(PrintDocumentService::class);
        $this->app->singleton(GoodsReceiptService::class);
        $this->app->singleton(SupplierAnalyticsService::class);
        $this->app->singleton(InventoryService::class);
        $this->app->singleton(FifoService::class);
        $this->app->singleton(BatchService::class);
        $this->app->singleton(ExpiryMonitoringService::class);
        $this->app->singleton(InventoryValuationService::class);
        $this->app->singleton(InventoryAnalyticsService::class);
        $this->app->singleton(SalesOrderService::class);
        $this->app->singleton(ReservationService::class);
        $this->app->singleton(FulfillmentService::class);
        $this->app->singleton(PosService::class);
        $this->app->singleton(InvoiceService::class);
        $this->app->singleton(PaymentService::class);
        $this->app->singleton(ReceiptService::class);
        $this->app->singleton(SalesReturnService::class);
        $this->app->singleton(PurchaseReturnService::class);
        $this->app->singleton(CreditNoteService::class);
        $this->app->singleton(RefundService::class);
        $this->app->singleton(SalesReportService::class);
        $this->app->singleton(ProfitAnalysisService::class);
        $this->app->singleton(InventoryReportService::class);
        $this->app->singleton(CustomerReportService::class);
        $this->app->singleton(SupplierReportService::class);
        $this->app->singleton(ProcurementReportService::class);
        $this->app->singleton(TaxReportService::class);
        $this->app->singleton(PaymentReportService::class);
        $this->app->singleton(DashboardAnalyticsService::class);
        $this->app->singleton(KpiService::class);
        $this->app->singleton(ScheduledReportService::class);
        $this->app->singleton(AdvanceService::class);
        $this->app->singleton(BankingService::class);
        $this->app->singleton(ExportService::class);
        $this->app->singleton(DocumentNumberingService::class);
        $this->app->singleton(DashboardCardService::class);
    }

    public function boot(): void
    {
        Category::observe(AuditObserver::class);
        Customer::observe(CustomerObserver::class);
        Customer::observe(AuditObserver::class);
        CustomerCreditTransaction::observe(AuditObserver::class);
        CustomerGroup::observe(AuditObserver::class);
        Group::observe(AuditObserver::class);
        Menu::observe(AuditObserver::class);
        PriceList::observe(PriceListObserver::class);
        PriceList::observe(AuditObserver::class);
        PriceListItem::observe(PriceListItemObserver::class);
        PriceListItem::observe(AuditObserver::class);
        Product::observe(ProductObserver::class);
        Product::observe(AuditObserver::class);
        Setting::observe(AuditObserver::class);
        PurchaseOrder::observe(PurchaseOrderObserver::class);
        PurchaseOrder::observe(AuditObserver::class);
        GoodsReceipt::observe(GoodsReceiptObserver::class);
        GoodsReceipt::observe(AuditObserver::class);
        SalesOrder::observe(SalesOrderObserver::class);
        SalesOrder::observe(AuditObserver::class);
        StockAdjustment::observe(AuditObserver::class);
        Supplier::observe(AuditObserver::class);
        Unit::observe(AuditObserver::class);
        Invoice::observe(InvoiceObserver::class);
        Invoice::observe(AuditObserver::class);
        Payment::observe(PaymentObserver::class);
        Payment::observe(AuditObserver::class);
        SalesReturn::observe(ReturnObserver::class);
        SalesReturn::observe(AuditObserver::class);
        PurchaseReturn::observe(PurchaseReturnObserver::class);
        PurchaseReturn::observe(AuditObserver::class);
        CreditNote::observe(CreditNoteObserver::class);
        CreditNote::observe(AuditObserver::class);
        JournalEntryLine::observe(JournalEntryLineObserver::class);

        Gate::define('edit', fn ($user) => $user->hasMenuAccess('invoices.index', 'can_edit'));
        Gate::define('delete', fn ($user) => $user->hasMenuAccess('invoices.index', 'can_delete'));
    }
}